#!/usr/bin/env python3
"""FastMCP entrypoint for USCardForum."""
from __future__ import annotations

from uscardforum.server_core import (
    MCP_HOST,
    MCP_PORT,
    MCP_TRANSPORT,
    NITAN_TOKEN,
    SERVER_INSTRUCTIONS,
    get_client,
    main,
    mcp,
)
from uscardforum.server_tools import (
    analyze_user,
    bookmark_post,
    compare_cards,
    find_data_points,
    get_all_topic_posts,
    get_categories,
    get_current_session,
    get_hot_topics,
    get_new_topics,
    get_notifications,
    get_top_topics,
    get_topic_info,
    get_topic_posts,
    get_user_actions,
    get_user_badges,
    get_user_followers,
    get_user_following,
    get_user_reactions,
    get_user_replies,
    get_user_summary,
    get_user_topics,
    list_users_with_badge,
    login,
    research_topic,
    resource_categories,
    resource_hot_topics,
    resource_new_topics,
    search_forum,
    subscribe_topic,
)

__all__ = [
    "MCP_HOST",
    "MCP_PORT",
    "MCP_TRANSPORT",
    "NITAN_TOKEN",
    "SERVER_INSTRUCTIONS",
    "get_client",
    "main",
    "mcp",
    "analyze_user",
    "bookmark_post",
    "compare_cards",
    "find_data_points",
    "get_all_topic_posts",
    "get_categories",
    "get_current_session",
    "get_hot_topics",
    "get_new_topics",
    "get_notifications",
    "get_top_topics",
    "get_topic_info",
    "get_topic_posts",
    "get_user_actions",
    "get_user_badges",
    "get_user_followers",
    "get_user_following",
    "get_user_reactions",
    "get_user_replies",
    "get_user_summary",
    "get_user_topics",
    "list_users_with_badge",
    "login",
    "resource_categories",
    "resource_hot_topics",
    "resource_new_topics",
    "search_forum",
    "subscribe_topic",
    "research_topic",
]


if __name__ == "__main__":
    main()
